/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.parser.node;
import soot.*;

public class NoCast implements Cast
{
    public NoCast( Singletons.Global g ) {}
    public static NoCast v() { return G.v().NoCast(); }

    public Object cast(Object o)
    {
        return o;
    }
}
