/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.parser.node;
import soot.*;

public class NodeCast implements Cast
{
    public NodeCast( Singletons.Global g ) {}
    public static NodeCast v() { return G.v().NodeCast(); }

    public Object cast(Object o)
    {
        return (Node) o;
    }
}
