#!/bin/sh
cat <<EOF
/* Soot - a J*va Optimization Framework
 * Copyright (C) 2003 Ondrej Lhotak
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/*
 * Modified by the Sable Research Group and others 1997-1999.  
 * See the 'credits' file distributed with Soot for the complete list of
 * contributors.  (Soot is distributed at http://www.sable.mcgill.ca/soot)
 */

package soot;
EOF

sed 's/^/import /g' package.list | sed 's/$/.*;/g'

echo
echo '/** A class to group together all the global variables in Soot. */'
echo 'public class Singletons {'
echo '    public final class Global {'
echo '        private Global() {}'
echo '    }'
echo '    private Global g = new Global();'
echo

for class in `cat singletons.list`; do
    echo "    private $class instance$class;"
    echo "    public $class $class() {"
    echo "        if( instance$class == null ) instance$class = new $class( g );"
    echo "        return instance$class;"
    echo "    }"
    echo
done

echo }

