class Cat1Cat2 extends java.lang.Object
{

    public void <init>()
    {
        word r0;

        r0 := @this: Cat1Cat2;
        load.r r0;
        specialinvoke <java.lang.Object: void <init>()>;
        return;
    }

    public static java.lang.Long testCaseHart()
    {
        new java.lang.Long;
        dup1.r;
        staticinvoke <Cat1Cat2: long f()>;
        specialinvoke <java.lang.Long: void <init>(long)>;
        return.r;
    }

    private static long f()
    {
        push 1L;
        return.l;
    }

    private static float g()
    {
        push 1.0F;
        return.f;
    }

    public static void test_dup_x2_cat1(float, float, int)
    {
        word f0, f1, i0;

        f0 := @parameter0: float;
        f1 := @parameter1: float;
        i0 := @parameter2: int;
        load.i i0;
        load.f f0;
        load.f f1;
        load.i i0;
        staticinvoke <Cat1Cat2: void printStack(int,float,float,int)>;
        return;
    }

    public static void test_dup_x2_cat2(long, int)
    {
        dword l0;
        word i1;

        l0 := @parameter0: long;
        i1 := @parameter1: int;
        load.i i1;
        load.l l0;
        load.i i1;
        staticinvoke <Cat1Cat2: void printStack(int,long,int)>;
        return;
    }

    public static void test_pop2_cat1(int, float, float)
    {
        word i0, f0, f1;

        i0 := @parameter0: int;
        f0 := @parameter1: float;
        f1 := @parameter2: float;
        load.i i0;
        staticinvoke <Cat1Cat2: void printStack(int)>;
        staticinvoke <Cat1Cat2: float g()>;
        pop;
        staticinvoke <Cat1Cat2: float g()>;
        pop;
        load.i i0;
        staticinvoke <Cat1Cat2: void printStack(int)>;
        return;
    }

    public static void test_pop2_cat2(int, long)
    {
        word i0;
        dword l1;

        i0 := @parameter0: int;
        l1 := @parameter1: long;
        load.i i0;
        staticinvoke <Cat1Cat2: void printStack(int)>;
        staticinvoke <Cat1Cat2: long f()>;
        pop;
        load.i i0;
        staticinvoke <Cat1Cat2: void printStack(int)>;
        return;
    }

    public static void test_dup2_cat1(int, float, float)
    {
        word i0, f0, f1;

        i0 := @parameter0: int;
        f0 := @parameter1: float;
        f1 := @parameter2: float;
        load.i i0;
        load.f f0;
        load.f f1;
        load.f f0;
        load.f f1;
        staticinvoke <Cat1Cat2: void printStack(int,float,float,float,float)>;
        return;
    }

    public static void test_dup2_cat2(int, double)
    {
        word i0;
        dword d0;

        i0 := @parameter0: int;
        d0 := @parameter1: double;
        load.i i0;
        load.d d0;
        load.d d0;
        staticinvoke <Cat1Cat2: void printStack(int,double,double)>;
        return;
    }

    public static void test_dup2_x1_cat1(int, float, float)
    {
        word i0, f0, f1;

        i0 := @parameter0: int;
        f0 := @parameter1: float;
        f1 := @parameter2: float;
        load.f f0;
        load.f f1;
        load.i i0;
        load.f f0;
        load.f f1;
        staticinvoke <Cat1Cat2: void printStack(float,float,int,float,float)>;
        return;
    }

    public static void test_dup2_x1_cat2(int, double)
    {
        word i0;
        dword d0;

        i0 := @parameter0: int;
        d0 := @parameter1: double;
        load.d d0;
        load.i i0;
        load.d d0;
        staticinvoke <Cat1Cat2: void printStack(double,int,double)>;
        return;
    }

    public static void test_dup2_x2_cat1cat1(int, float, float, int, int)
    {
        word i0, f0, f1, i1, i2;

        i0 := @parameter0: int;
        f0 := @parameter1: float;
        f1 := @parameter2: float;
        i1 := @parameter3: int;
        i2 := @parameter4: int;
        load.i i0;
        load.i i1;
        load.i i2;
        load.f f0;
        load.f f1;
        load.i i1;
        load.i i2;
        staticinvoke <Cat1Cat2: void printStack(int,int,int,float,float,int,int)>;
        return;
    }

    public static void test_dup2_x2_cat1cat2(int, float, float, double)
    {
        word i0, f0, f1;
        dword d0;

        i0 := @parameter0: int;
        f0 := @parameter1: float;
        f1 := @parameter2: float;
        d0 := @parameter3: double;
        load.i i0;
        load.d d0;
        load.f f0;
        load.f f1;
        load.d d0;
        staticinvoke <Cat1Cat2: void printStack(int,double,float,float,double)>;
        return;
    }

    public static void test_dup2_x2_cat2cat1(int, long, float, float)
    {
        word i0, f0, f1;
        dword l1;

        i0 := @parameter0: int;
        l1 := @parameter1: long;
        f0 := @parameter2: float;
        f1 := @parameter3: float;
        load.i i0;
        load.f f0;
        load.f f1;
        load.l l1;
        load.f f0;
        load.f f1;
        staticinvoke <Cat1Cat2: void printStack(int,float,float,long,float,float)>;
        return;
    }

    public static void test_dup2_x2_cat2cat2(int, long, double)
    {
        word i0;
        dword l1, d0;

        i0 := @parameter0: int;
        l1 := @parameter1: long;
        d0 := @parameter2: double;
        load.i i0;
        load.d d0;
        load.l l1;
        load.d d0;
        staticinvoke <Cat1Cat2: void printStack(int,double,long,double)>;
        return;
    }

    public static void printStack(int, float, float, int)
    {
        word i0, f0, f1, i1, r0;

        i0 := @parameter0: int;
        f0 := @parameter1: float;
        f1 := @parameter2: float;
        i1 := @parameter3: int;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.f f0;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f1;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.i i1;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(int, long, int)
    {
        word i0, i2, r0;
        dword l1;

        i0 := @parameter0: int;
        l1 := @parameter1: long;
        i2 := @parameter2: int;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.l l1;
        virtualinvoke <java.io.PrintStream: void println(long)>;
        load.r r0;
        load.i i2;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(int)
    {
        word i0;

        i0 := @parameter0: int;
        staticget <java.lang.System: java.io.PrintStream out>;
        dup1.r;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(int, float, float, float, float)
    {
        word i0, f0, f1, f2, f3, r0;

        i0 := @parameter0: int;
        f0 := @parameter1: float;
        f1 := @parameter2: float;
        f2 := @parameter3: float;
        f3 := @parameter4: float;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.f f0;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f1;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f2;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f3;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(int, double, double)
    {
        word i0, r0;
        dword d0, d1;

        i0 := @parameter0: int;
        d0 := @parameter1: double;
        d1 := @parameter2: double;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.d d0;
        virtualinvoke <java.io.PrintStream: void println(double)>;
        load.r r0;
        load.d d1;
        virtualinvoke <java.io.PrintStream: void println(double)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(float, float, int, float, float)
    {
        word f0, f1, i0, f2, f3, r0;

        f0 := @parameter0: float;
        f1 := @parameter1: float;
        i0 := @parameter2: int;
        f2 := @parameter3: float;
        f3 := @parameter4: float;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.f f0;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f1;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.f f2;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f3;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(double, int, double)
    {
        dword d0, d1;
        word i0, r0;

        d0 := @parameter0: double;
        i0 := @parameter1: int;
        d1 := @parameter2: double;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.d d0;
        virtualinvoke <java.io.PrintStream: void println(double)>;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.d d1;
        virtualinvoke <java.io.PrintStream: void println(double)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(int, int, int, float, float, int, int)
    {
        word i0, i1, i2, f0, f1, i3, i4, r0;

        i0 := @parameter0: int;
        i1 := @parameter1: int;
        i2 := @parameter2: int;
        f0 := @parameter3: float;
        f1 := @parameter4: float;
        i3 := @parameter5: int;
        i4 := @parameter6: int;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.i i1;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.i i2;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.f f0;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f1;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.i i3;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.i i4;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(int, double, float, float, double)
    {
        word i0, f0, f1, r0;
        dword d0, d1;

        i0 := @parameter0: int;
        d0 := @parameter1: double;
        f0 := @parameter2: float;
        f1 := @parameter3: float;
        d1 := @parameter4: double;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.d d0;
        virtualinvoke <java.io.PrintStream: void println(double)>;
        load.r r0;
        load.f f0;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f1;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.d d1;
        virtualinvoke <java.io.PrintStream: void println(double)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(int, float, float, long, float, float)
    {
        word i0, f0, f1, f2, f3, r0;
        dword l1;

        i0 := @parameter0: int;
        f0 := @parameter1: float;
        f1 := @parameter2: float;
        l1 := @parameter3: long;
        f2 := @parameter4: float;
        f3 := @parameter5: float;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.f f0;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f1;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.l l1;
        virtualinvoke <java.io.PrintStream: void println(long)>;
        load.r r0;
        load.f f2;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        load.f f3;
        virtualinvoke <java.io.PrintStream: void println(float)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void printStack(int, double, long, double)
    {
        word i0, r0;
        dword d0, l1, d1;

        i0 := @parameter0: int;
        d0 := @parameter1: double;
        l1 := @parameter2: long;
        d1 := @parameter3: double;
        staticget <java.lang.System: java.io.PrintStream out>;
        store.r r0;
        load.r r0;
        load.i i0;
        virtualinvoke <java.io.PrintStream: void println(int)>;
        load.r r0;
        load.d d0;
        virtualinvoke <java.io.PrintStream: void println(double)>;
        load.r r0;
        load.l l1;
        virtualinvoke <java.io.PrintStream: void println(long)>;
        load.r r0;
        load.d d1;
        virtualinvoke <java.io.PrintStream: void println(double)>;
        load.r r0;
        virtualinvoke <java.io.PrintStream: void println()>;
        return;
    }

    public static void main(java.lang.String[])
    {
        word r0;

        r0 := @parameter0: java.lang.String[];
        push 1.1111F;
        push 2.2222F;
        push 3;
        staticinvoke <Cat1Cat2: void test_dup_x2_cat1(float,float,int)>;
        push 11111L;
        push 2;
        staticinvoke <Cat1Cat2: void test_dup_x2_cat2(long,int)>;
        push 1;
        push 2.2222F;
        push 3.3333F;
        staticinvoke <Cat1Cat2: void test_pop2_cat1(int,float,float)>;
        push 1;
        push 22222L;
        staticinvoke <Cat1Cat2: void test_pop2_cat2(int,long)>;
        push 1;
        push 2.2222F;
        push 3.3333F;
        staticinvoke <Cat1Cat2: void test_dup2_cat1(int,float,float)>;
        push 1;
        push 2.2222;
        staticinvoke <Cat1Cat2: void test_dup2_cat2(int,double)>;
        push 1;
        push 2.2222F;
        push 3.3333F;
        staticinvoke <Cat1Cat2: void test_dup2_x1_cat1(int,float,float)>;
        push 1;
        push 2.2222;
        staticinvoke <Cat1Cat2: void test_dup2_x1_cat2(int,double)>;
        push 1;
        push 2.222F;
        push 3.333F;
        push 4;
        push 5;
        staticinvoke <Cat1Cat2: void test_dup2_x2_cat1cat1(int,float,float,int,int)>;
        push 1;
        push 2.222F;
        push 3.333F;
        push 4444.44444;
        staticinvoke <Cat1Cat2: void test_dup2_x2_cat1cat2(int,float,float,double)>;
        push 1;
        push 2222222L;
        push 3.3333F;
        push 4.4444F;
        staticinvoke <Cat1Cat2: void test_dup2_x2_cat2cat1(int,long,float,float)>;
        push 1;
        push 2222222L;
        push 3333.3333;
        staticinvoke <Cat1Cat2: void test_dup2_x2_cat2cat2(int,long,double)>;
        return;
    }
}
