/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.17u-20021128-1508
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package soot.jbuddy;


public class bddCacheStat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected bddCacheStat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      JBuddyJNI.delete_bddCacheStat(swigCPtr);
      swigCMemOwn = false;
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(bddCacheStat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void setUniqueAccess(long uniqueAccess) {
    JBuddyJNI.set_bddCacheStat_uniqueAccess(swigCPtr, uniqueAccess);
  }

  public long getUniqueAccess() {
    return JBuddyJNI.get_bddCacheStat_uniqueAccess(swigCPtr);
  }

  public void setUniqueChain(long uniqueChain) {
    JBuddyJNI.set_bddCacheStat_uniqueChain(swigCPtr, uniqueChain);
  }

  public long getUniqueChain() {
    return JBuddyJNI.get_bddCacheStat_uniqueChain(swigCPtr);
  }

  public void setUniqueHit(long uniqueHit) {
    JBuddyJNI.set_bddCacheStat_uniqueHit(swigCPtr, uniqueHit);
  }

  public long getUniqueHit() {
    return JBuddyJNI.get_bddCacheStat_uniqueHit(swigCPtr);
  }

  public void setUniqueMiss(long uniqueMiss) {
    JBuddyJNI.set_bddCacheStat_uniqueMiss(swigCPtr, uniqueMiss);
  }

  public long getUniqueMiss() {
    return JBuddyJNI.get_bddCacheStat_uniqueMiss(swigCPtr);
  }

  public void setOpHit(long opHit) {
    JBuddyJNI.set_bddCacheStat_opHit(swigCPtr, opHit);
  }

  public long getOpHit() {
    return JBuddyJNI.get_bddCacheStat_opHit(swigCPtr);
  }

  public void setOpMiss(long opMiss) {
    JBuddyJNI.set_bddCacheStat_opMiss(swigCPtr, opMiss);
  }

  public long getOpMiss() {
    return JBuddyJNI.get_bddCacheStat_opMiss(swigCPtr);
  }

  public void setSwapCount(long swapCount) {
    JBuddyJNI.set_bddCacheStat_swapCount(swigCPtr, swapCount);
  }

  public long getSwapCount() {
    return JBuddyJNI.get_bddCacheStat_swapCount(swigCPtr);
  }

  public bddCacheStat() {
    this(JBuddyJNI.new_bddCacheStat(), true);
  }

}
