/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.17u-20021128-1508
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package soot.jbuddy;


public class bddGbcStat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected bddGbcStat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      JBuddyJNI.delete_bddGbcStat(swigCPtr);
      swigCMemOwn = false;
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(bddGbcStat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void setNodes(int nodes) {
    JBuddyJNI.set_bddGbcStat_nodes(swigCPtr, nodes);
  }

  public int getNodes() {
    return JBuddyJNI.get_bddGbcStat_nodes(swigCPtr);
  }

  public void setFreenodes(int freenodes) {
    JBuddyJNI.set_bddGbcStat_freenodes(swigCPtr, freenodes);
  }

  public int getFreenodes() {
    return JBuddyJNI.get_bddGbcStat_freenodes(swigCPtr);
  }

  public void setTime(int time) {
    JBuddyJNI.set_bddGbcStat_time(swigCPtr, time);
  }

  public int getTime() {
    return JBuddyJNI.get_bddGbcStat_time(swigCPtr);
  }

  public void setSumtime(int sumtime) {
    JBuddyJNI.set_bddGbcStat_sumtime(swigCPtr, sumtime);
  }

  public int getSumtime() {
    return JBuddyJNI.get_bddGbcStat_sumtime(swigCPtr);
  }

  public void setNum(int num) {
    JBuddyJNI.set_bddGbcStat_num(swigCPtr, num);
  }

  public int getNum() {
    return JBuddyJNI.get_bddGbcStat_num(swigCPtr);
  }

  public bddGbcStat() {
    this(JBuddyJNI.new_bddGbcStat(), true);
  }

}
