/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.17u-20021128-1508
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package soot.jbuddy;


public class bddPair {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected bddPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      JBuddyJNI.delete_bddPair(swigCPtr);
      swigCMemOwn = false;
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(bddPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void setResult(SWIGTYPE_p_int result) {
    JBuddyJNI.set_bddPair_result(swigCPtr, SWIGTYPE_p_int.getCPtr(result));
  }

  public SWIGTYPE_p_int getResult() {
    long cPtr = JBuddyJNI.get_bddPair_result(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setLast(int last) {
    JBuddyJNI.set_bddPair_last(swigCPtr, last);
  }

  public int getLast() {
    return JBuddyJNI.get_bddPair_last(swigCPtr);
  }

  public void setId(int id) {
    JBuddyJNI.set_bddPair_id(swigCPtr, id);
  }

  public int getId() {
    return JBuddyJNI.get_bddPair_id(swigCPtr);
  }

  public void setNext(bddPair next) {
    JBuddyJNI.set_bddPair_next(swigCPtr, bddPair.getCPtr(next));
  }

  public bddPair getNext() {
    long cPtr = JBuddyJNI.get_bddPair_next(swigCPtr);
    return (cPtr == 0) ? null : new bddPair(cPtr, false);
  }

  public bddPair() {
    this(JBuddyJNI.new_bddPair(), true);
  }

}
