/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.17u-20021128-1508
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package soot.jbuddy;


public class SWIGTYPE_p_FILE {
  private long swigCPtr;

  protected SWIGTYPE_p_FILE(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_FILE() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_FILE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

