/* This file was generated by SableCC (http://www.sable.mcgill.ca/sablecc/). */

package soot.jimple.parser.parser;

public class ParserException extends Exception
{
    public ParserException(String  message)
    {
        super(message);
    }
}
